---
- name: Test
  hosts: webserver
  user: sysadmin
  become: yes

  tasks:

    - name: Paquete este presente http (centos)
      yum:
        pkg: httpd
        state: latest
      when: ansible_facts['os_family'] == 'Redhat'
      notify: Reiniciar httpd


    - name: Paquete este presente http (ubuntu)
      apt:
        pkg: apache2
        state: latest
      when: ansible_facts['os_family'] == 'Debian'
      notify: Reiniciar apache2


    - name: Ultimo index.html presente
      copy:
        src: ./files/index.html
        dest: /var/www/html/index.html
      notify: Reiniciar httpd

    
    - name: Permitir http en firewall
      ansible.posix.firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: true
        offline: true
      when: ansible_facts['os_family'] == 'Redhat'



    - name: Habilitar puerto SSSH/22 en ufw
      community.general.ufw:
        rule: allow
        port: ssh
        proto: tcp
        state: enabled
      when: ansible_facts['os_family'] == 'Debian'


    - name: Habilitar puerto HTTP/80 en ufw
      community.general.ufw:
        rule: allow
        port: http
        proto: tcp
        state: enabled
      when: ansible_facts['os_family'] == 'Debian'



  handlers: 
    - name: Reiniciar httpd
      service:
        name: httpd
        state: restarted
      when: ansible_facts['os_family'] == 'Redhat'


    - name: Reiniciar apache2
      service:
        name: apache2
        state: restarted
      when: ansible_facts['os_family'] == 'Debian'
